from __future__ import annotations

import argparse
from collections.abc import Mapping
import json
from pathlib import Path
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agent_runtime.drift.drift_suite import DriftSuiteFinding, DriftSuiteReport


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a repo-health issue body from a drift suite JSON report.")
    parser.add_argument("--report", required=True, help="Path to `latest_report.json` generated by `scripts/drift/run_all.py`.")
    parser.add_argument("--output", help="Optional markdown output path.")
    return parser.parse_args()


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

    from agent_runtime.drift.drift_suite import render_drift_suite_issue_body

    args = parse_args()
    report_path = Path(args.report)
    payload = json.loads(report_path.read_text(encoding="utf-8"))
    body = render_drift_suite_issue_body(_report_from_payload(payload))
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(body + "\n", encoding="utf-8")
    print(body)
    return 0


def _report_from_payload(payload: dict[str, object]) -> "DriftSuiteReport":
    from agent_runtime.drift.drift_suite import DriftSuiteReport, DriftSuiteStats, DriftScanSummary

    raw_scans = payload["scans"]
    assert isinstance(raw_scans, list)
    raw_findings = payload["findings"]
    assert isinstance(raw_findings, list)
    raw_waived_findings = payload["waived_findings"]
    assert isinstance(raw_waived_findings, list)
    raw_stats = payload["stats"]
    assert isinstance(raw_stats, dict)

    return DriftSuiteReport(
        scan_name=str(payload["scan_name"]),
        root=str(payload["root"]),
        generated_at=str(payload["generated_at"]),
        baseline_path=str(payload["baseline_path"]),
        scans=tuple(
            DriftScanSummary(
                scan_name=str(scan["scan_name"]),
                title=str(scan["title"]),
                artifact_path=str(scan["artifact_path"]),
                stats=_mapping_to_dict(scan["stats"]),
                total_findings=int(scan["total_findings"]),
                new_findings=tuple(_finding_from_payload(item) for item in scan["new_findings"]),
                waived_findings=tuple(_finding_from_payload(item) for item in scan["waived_findings"]),
            )
            for scan in raw_scans
        ),
        findings=tuple(_finding_from_payload(item) for item in raw_findings),
        waived_findings=tuple(_finding_from_payload(item) for item in raw_waived_findings),
        stats=DriftSuiteStats(
            scans_run=int(raw_stats["scans_run"]),
            total_findings=int(raw_stats["total_findings"]),
            new_findings=int(raw_stats["new_findings"]),
            waived_findings=int(raw_stats["waived_findings"]),
        ),
    )


def _finding_from_payload(item: object) -> "DriftSuiteFinding":
    from agent_runtime.drift.drift_suite import DriftSuiteFinding

    assert isinstance(item, dict)
    return DriftSuiteFinding(
        scan_name=str(item["scan_name"]),
        signature=str(item["signature"]),
        kind=str(item["kind"]),
        severity=str(item["severity"]),
        drift_class=str(item["drift_class"]),
        owner=str(item["owner"]),
        message=str(item["message"]),
        raw_finding=dict(item["raw_finding"]),
        rationale=None if item.get("rationale") is None else str(item["rationale"]),
        issue=None if item.get("issue") is None else str(item["issue"]),
        expires_on=None if item.get("expires_on") is None else str(item["expires_on"]),
    )


def _mapping_to_dict(value: object) -> dict[str, object]:
    assert isinstance(value, Mapping)
    return {str(key): item for key, item in value.items()}


if __name__ == "__main__":
    raise SystemExit(main())
