from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a repo-health issue body from a drift suite JSON report.")
    parser.add_argument("--report", required=True, help="Path to `latest_report.json` generated by `scripts/drift/run_all.py`.")
    parser.add_argument("--output", help="Optional markdown output path.")
    return parser.parse_args()


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

    from agent_runtime.drift.drift_suite import DriftSuiteReport, render_drift_suite_issue_body

    args = parse_args()
    payload = json.loads(Path(args.report).read_text(encoding="utf-8"))
    report = DriftSuiteReport.from_dict(payload)
    body = render_drift_suite_issue_body(report)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(body + "\n", encoding="utf-8")
    print(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
